name: purchasing_lanka_international
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.0.0
  meta: ^1.1.6
  equatable: ^0.6.1
  carousel_pro: ^0.0.13
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2
  shared_preferences: ^0.4.3
  loading: ^1.0.1
  clock: ^1.0.1
  path_provider: ^1.5.0
  image_picker: ^0.6.2
  path: ^1.6.4
  camera: ^0.5.7+4
  flutter_country_picker: ^0.1.6
  material_design_icons_flutter: ^3.4.4795
  sticky_headers: ^0.1.7
  intl: ^0.16.1
  responsive_container:
  stripe_payment: ^1.0.6
  uni_links: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/backgrounds/
    - assets/adds/
    - assets/icon/
    - assets/catogory/
    - assets/backgrounds/splash.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 700
    - family: Goicon
      fonts:
        - asset: assets/GoIcon.ttf
    - family: Georgia
      fonts:
        - asset: assets/georgia.ttf

    - family: Apple
      fonts:
        - asset: fonts/Apple-Chancery.ttf

    - family: Lato
      fonts:
        - asset: assets/Lato.ttf
        - asset: assets/Lato-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700 georgia.ttf
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
